enhancement : Add a Footer
MLH-Fellowship/prep-portfolio-22.JUL.PREP.2 pull request #21
Opened 2022-07-13 16:27 UTC by jhashivam-2001

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

📷 Screenshots of the addition :- 

![image](https://user-images.githubusercontent.com/76417298/178922793-35b7a1aa-bf96-4001-a844-487b213b0696.png)

closes #1

2022-07-13 17:17 UTC, sumana2001 requested changes
Couple of things to work on:

1. The design looks a bit off on my laptop, seems like there is some extra white portion blocking the footer at the end. Please also check the same in mobile view
<img width="1552" alt="Screenshot 2022-07-13 at 10 41 38 PM" src="https://user-images.githubusercontent.com/63084088/178791708-c66a438d-72e6-41f3-a3f0-aa532a2eca67.png">

2. I am concerned about the design because most of it is empty. I think it will be better if you can distribute the content among the footer uniformly, and either make a thinner footer or maybe add some more things like a small description about MLH or the fellowship. 
3. The useful links aren't linked to anything

Feel free to take inputs from everyone in the pod using our pod-chat discord channel.

2022-07-14 07:25 UTC, sumana2001 requested changes
Is there a reason for adding half the CSS in main.scss and half in footer.scss? Won't it be more convenient if all the footer CSS is in the footer.scss file?

2022-07-14 07:42 UTC, jhashivam-2001 commented
> 

There were some conflicting css rules which I was'nt able to resolve so I left things as they were , but now it's all settled .

2022-07-14 07:44 UTC, sumana2001 approved these changes

2022-07-14 07:44 UTC, merged